### ISSUE TITLE
加密报错

### ISSUE THREAD

**Issue by BugRui** [smallbuer/flutter_aes_ecb_pkcs5#2]
Unhandled Exception: MissingPluginException(No implementation found for method encrypt on channel flutter_aes_ecb_pkcs5)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#2      FlutterAesEcbPkcs5.encryptString (package:flutter_aes_ecb_pkcs5/flutter_aes_ecb_pkcs5.dart:40:26)
#3      EncryptHelper.encode (package:zyb/utils/EncryptHelper.dart:24:37)
#4      DioUtils.postHttp (package:zyb/net/DioUtils.dart:70:24)
#5      AdvertisingPage.createState (package:zyb/widgets/advertising_page.dart:12:14)
#6      new StatefulElement (package:flutter/src/widgets/framework.dart:4635:25)
#7      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:900:38)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3485:40)
#9      Element.updateChild (package:flutter/src/widgets/fram<…>

**Comment by smallbuer** [comment]
> Unhandled Exception: MissingPluginException(No implementation found for method encrypt on channel flutter_aes_ecb_pkcs5)
> #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
> 
> #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
> #2 FlutterAesEcbPkcs5.encryptString (package:flutter_aes_ecb_pkcs5/flutter_aes_ecb_pkcs5.dart:40:26)
> #3 EncryptHelper.encode (package:zyb/utils/EncryptHelper.dart:24:37)
> #4 DioUtils.postHttp (package:zyb/net/DioUtils.dart:70:24)
> #5 AdvertisingPage.createState (package:zyb/widgets/advertising_page.dart:12:14)
> #6 new StatefulElement (package:flutter/src/widgets/framework.dart:4635:25)
> #7 StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:900:38)
> #8 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3485:40)
> #9 Element.updateChild (package:flutter/src/widgets/fram<…>

请问是什么平台报的这个错误？IOS和android平台均测试通过

**Comment by smallbuer** [comment]
请检查flutter开发环境是否匹配
