### ISSUE TITLE
这玩意 练案例都跑不通啊

### ISSUE THREAD

**Issue by Xiaoqi-01** [smallbuer/flutter_aes_ecb_pkcs5#5]
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method generateDesKey on channel flutter_aes_ecb_pkcs5)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      FlutterAesEcbPkcs5.generateDesKey (package:flutter_aes_ecb_pkcs5_fork/flutter_aes_ecb_pkcs5_fork.dart:27:11)
<asynchronous suspension>
#2      _VideoDataState.downApkFunction (package:media_app/pages/video_data.dart:49:15)
<asynchronous suspension>

**Comment by smallbuer** [comment]
请检查环境是否配置正确
