### ISSUE TITLE
Flutter 3: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by poka-IT** [smallbuer/flutter_aes_ecb_pkcs5#7]
Since Flutter 3.0, there is new warnings:

```
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/lib/responsive_wrapper.dart:622
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Apps/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addObserver(this);
                   ^
```

**Comment by smallbuer** [comment]
> Since Flutter 3.0, there is new warnings:
> 
> ```
> : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> ../…/lib/responsive_wrapper.dart:622
> - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Apps/flutter/packages/flutter/lib/src/widgets/binding.dart').
> package:flutter/…/widgets/binding.dart:1
>     WidgetsBinding.instance!.addObserver(this);
>                    ^
> ```

应该不是这个库的问题
