### ISSUE TITLE
求助作者,与在线结果不一致

### ISSUE THREAD

**Issue by jackTang11** [smallbuer/flutter_aes_ecb_pkcs5#8]
为什么在 (http://tool.chacuo.net/cryptaes)  网站上加密之后的结果不一样,而且无法解密

![WX20221105-101725](https://user-images.githubusercontent.com/7345590/200096758-0603eacf-fdb8-4d6f-bdeb-307d7d0293bd.png)

String token = 'thingquitventureenough owner uselesschestrapidcomicreunionfoodgarage';
String key = '5371a97bf39c7b40088894a3b6d57931';
 String result = await FlutterAesEcbPkcs5.encryptString(token, key);

AE9C0C8BFCAE37878E6B0BDA57AD1C5A2C483A43B877D6865CFB8BCCB0871B97B4B6712E3602AC487084CDA8C0AD10538A2A70DBFE829082BA2F838B2CF4A1801F3F381F473D424CE61FDC5F91EA7CBA

**Comment by smallbuer** [comment]
> 为什么在 (http://tool.chacuo.net/cryptaes) 网站上加密之后的结果不一样,而且无法解密
> 
> ![WX20221105-101725](https://user-images.githubusercontent.com/7345590/200096758-0603eacf-fdb8-4d6f-bdeb-307d7d0293bd.png)
> 
> String token = 'thingquitventureenough owner uselesschestrapidcomicreunionfoodgarage'; String key = '5371a97bf39c7b40088894a3b6d57931'; String result = await FlutterAesEcbPkcs5.encryptString(token, key);
> 
> AE9C0C8BFCAE37878E6B0BDA57AD1C5A2C483A43B877D6865CFB8BCCB0871B97B4B6712E3602AC487084CDA8C0AD10538A2A70DBFE829082BA2F838B2CF4A1801F3F381F473D424CE61FDC5F91EA7CBA

因为此网站输入的密码是不带十六进制转换的值，比如你用flutter插入的key=31313131313131313131313131313131,在网站上应该输入 1111111111111111
